services:
  frontend:
    image: node:20
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: npm run dev -- --host

  backend:
    build: ./backend
    ports:
      - "8888:80"
    volumes:
      - ./backend:/var/www/backend
      - ./backend/public:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${sql_pass}
      MYSQL_DATABASE: ${sql_namedb}
      MYSQL_USER: ${sql_user}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: